<a href="https://colab.research.google.com/github/tushar2411/Play-Store-App-Reviews-Analysis/blob/main/Copy_of_Play_Store_App_Review_Analysis_Capstone_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## <b> The Play Store apps data has enormous potential to drive app-making businesses to success. Actionable insights can be drawn for developers to work on and capture the Android market. </b>

## <b> Each app (row) has values for catergory, rating, size, and more. Another dataset contains customer reviews of the android apps.</b>

## <b> Explore and analyze the data to discover key factors responsible for app engagement and success. </b>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [37]:
playApp1 = pd.read_csv('/content/drive/MyDrive/Alambetter/Capstone Project 1/Play Store App Review Analysis/Play Store Data.csv')

In [43]:
playApp1.shape

(10841, 13)

In [81]:
playApp2 = pd.read_csv('/content/drive/MyDrive/Alambetter/Capstone Project 1/Play Store App Review Analysis/User Reviews.csv')

In [82]:
playApp2.shape

(64295, 5)

##*Now, we have Two DataSets 1) Play store data and 2) User reviews. We will combine Data on common columns. Here, we have same column name 'App'. So we'll join it on this column.*

In [83]:
playdataF = pd.merge(playApp1,playApp2,on='App')

In [84]:
playdataF.shape

(122662, 17)

In [85]:
playdataF.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver', 'Translated_Review', 'Sentiment', 'Sentiment_Polarity',
       'Sentiment_Subjectivity'],
      dtype='object')

In [86]:
playdataF.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,A kid's excessive ads. The types ads allowed a...,Negative,-0.250,1.000000
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,It bad >:(,Negative,-0.725,0.833333
2,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,like,Neutral,0.000,0.000000
3,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,NaN,NaN,NaN,NaN
4,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,I love colors inspyering,Positive,0.500,0.600000

In [87]:
playdataF.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
122657,A+ Gallery - Photos & Videos,PHOTOGRAPHY,4.5,223941,Varies with device,"10,000,000+",Free,0,Everyone,Photography,"August 6, 2018",Varies with device,Varies with device,NaN,NaN,NaN,NaN
122658,A+ Gallery - Photos & Videos,PHOTOGRAPHY,4.5,223941,Varies with device,"10,000,000+",Free,0,Everyone,Photography,"August 6, 2018",Varies with device,Varies with device,NaN,NaN,NaN,NaN
122659,A+ Gallery - Photos & Videos,PHOTOGRAPHY,4.5,223941,Varies with device,"10,000,000+",Free,0,Everyone,Photography,"August 6, 2018",Varies with device,Varies with device,Too much ads,Positive,0.20,0.20
122660,A+ Gallery - Photos & Videos,PHOTOGRAPHY,4.5,223941,Varies with device,"10,000,000+",Free,0,Everyone,Photography,"August 6, 2018",Varies with device,Varies with device,Just allow time ...,Neutral,0.00,0.00
122661,A+ Gallery - Photos & Videos,PHOTOGRAPHY,4.5,223941,Varies with device,"10,000,000+",Free,0,Everyone,Photography,"August 6, 2018",Varies with device,Varies with device,It's good best gallery phone,Positive,0.85,0.45

In [88]:
data1  = playdataF.head()
data2  = playdataF.tail()
concatData = pd.concat([data1,data2],axis=0,ignore_index=True)

In [89]:
concatData

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,A kid's excessive ads. The types ads allowed a...,Negative,-0.250,1.000000
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,It bad >:(,Negative,-0.725,0.833333
2,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,like,Neutral,0.000,0.000000
3,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,NaN,NaN,NaN,NaN
4,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,I love colors inspyering,Positive,0.500,0.600000
5,A+ Gallery - Photos & Videos,PHOTOGRAPHY,4.5,223941,Varies with device,"10,000,000+",Free,0,Everyone,Photography,"August 6, 2018",Varies with device,Varies with device,NaN,NaN,NaN,NaN
6,A+ Gallery - Photos & Videos,PHOTOGRAPHY,4.5,223941,Varies with device,"10,000,000+",Free,0,Everyone,Photography,"August 6, 2018",Varies with device,Varies with device,NaN,NaN,NaN,NaN
7,A+ Gallery - Photos & Videos,PHOTOGRAPHY,4.5,223941,Varies with device,"10,000,000+",Free,0,Everyone,Photography,"August 6, 2018",Varies with device,Varies with device,Too much ads,Positive,0.200,0.200000
8,A+ Gallery - Photos & Videos,PHOTOGRAPHY,4.5,223941,Varies with device,"10,000,000+",Free,0,Everyone,Photography,"August 6, 2018",Varies with device,Varies with device,Just allow time ...,Neutral,0.000,0.000000
9,A+ Gallery - Photos & Videos,PHOTOGRAPHY,4.5,223941,Varies with device,"10,000,000+",Free,0,Everyone,Photography,"August 6, 2018",Varies with device,Varies with device,It's good best gallery phone,Positive,0.850,0.450000

In [90]:
playdataF.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 122662 entries, 0 to 122661
Data columns (total 17 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   App                     122662 non-null  object
 1   Category                122662 non-null  object
 2   Rating                  122622 non-null  float64
 3   Reviews                 122662 non-null  object
 4   Size                    122662 non-null  object
 5   Installs                122662 non-null  object
 6   Type                    122662 non-null  object
 7   Price                   122662 non-null  object
 8   Content Rating          122662 non-null  object
 9   Genres                  122662 non-null  object
 10  Last Updated            122662 non-null  object
 11  Current Ver             122662 non-null  object
 12  Android Ver             122662 non-null  object
 13  Translated_Review       72605 non-null   object
 14  Sentiment               72615 non-null   object
 15  Sentiment_Polarity      72615 non-null   float64
 16  Sentiment_Subjectivity  72615 non-null   float64
dtypes: float64(3), object(14)
memory usage: 16.8+ MB

#1) Data Cleaning

In [91]:
playdataF.describe()

              Rating  Sentiment_Polarity  Sentiment_Subjectivity
count  122622.000000        72615.000000            72615.000000
mean        4.322405            0.157320                0.494162
std         0.284766            0.332652                0.240144
min         2.500000           -1.000000                0.000000
25%         4.200000            0.000000                0.380000
50%         4.400000            0.129167                0.509740
75%         4.500000            0.356250                0.633333
max         4.900000            1.000000                1.000000

In [92]:
playdataF.isnull()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122657,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True
122658,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True
122659,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
122660,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
122661,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [93]:
playdataF.isnull().sum()

App                           0
Category                      0
Rating                       40
Reviews                       0
Size                          0
Installs                      0
Type                          0
Price                         0
Content Rating                0
Genres                        0
Last Updated                  0
Current Ver                   0
Android Ver                   0
Translated_Review         50057
Sentiment                 50047
Sentiment_Polarity        50047
Sentiment_Subjectivity    50047
dtype: int64

#*In Rating column we have some null values. To remove these values we'll calculate median of this column by creating function*

In [94]:
def cal_median(counts):
  return counts.fillna(counts.median)

In [95]:
playdataF.Rating = playdataF['Rating'].transform(cal_median)

#*Now we will apply this function for same the 'Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity'*

In [96]:
playdataF.Translated_Review = playdataF['Translated_Review'].transform(cal_median)

In [97]:
playdataF.Sentiment = playdataF['Sentiment'].transform(cal_median)

In [98]:
playdataF.Sentiment_Polarity = playdataF['Sentiment_Polarity'].transform(cal_median)

In [99]:
playdataF.Sentiment_Subjectivity = playdataF['Sentiment_Subjectivity'].transform(cal_median)

In [100]:
playdataF.isnull().sum()

App                       0
Category                  0
Rating                    0
Reviews                   0
Size                      0
Installs                  0
Type                      0
Price                     0
Content Rating            0
Genres                    0
Last Updated              0
Current Ver               0
Android Ver               0
Translated_Review         0
Sentiment                 0
Sentiment_Polarity        0
Sentiment_Subjectivity    0
dtype: int64

#*We can also see that above information about data there is a Price column which has all numeric float values plus there is $ sign we will remove it and convert into float values and also*

In [119]:
playdataF['Price'].unique()

array([0.0, '$6.99', '0', '$1.99', '$4.99', '$3.99', '$2.99', '$11.99',
       '$9.99', '$7.99', '$33.99', '$3.95', '$29.99', '$2.49', '$0.99'],
      dtype=object)

In [122]:
playdataF['Price'] = playdataF['Price'].astype('float')

ValueError: ignored

In [121]:
for i in range(0,len(playdataF['Price'])):
  if '$' in playdataF.loc[i,'Price']:
    playdataF.loc[i,'Price'] = playdataF.loc[i,'Price'][1:]
  playdataF.loc[i,'Price'] =  int(playdataF.loc[i,'Price'])

TypeError: ignored